### ISSUE TITLE
MedFlare : Create Home Page  for Website

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/MedFlare#1]
Hey JWOC participants, good to see you.

This issue's goal is to create an external layout of a home page of the website.

Feel free to be creative! And please take care of the following criteria:

- In the page, add About (uncopyrighted image along with introductory text), Services (6) and Why Choose Us (some pointers with intended graphics) sections excluding header and footer

How to get it approved?

- Add a screenshot of  outlook on this thread and wait for one of the mentors to get back to you.
- Once it's approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/MedFlare/blob/main/CONTRIBUTING.md) at least once before contributing code.

**Comment by SabariGanesh-K** [comment]
Hello. Would love to contribute. But no files are there in src that is responsible to render home page. So where should we find it and improvise?

**Comment by prathimacode-hub** [comment]
It's a new project so basically it should start from scratch. Yes. To get yourself assigned, kindly express your interest from 12AM 1st Feb. That's when the issue is valid for counting. Are you a JWoC Participant? @SabariGanesh-K

**Comment by SabariGanesh-K** [comment]
@prathimacode-hub  Yes yes.. JWOC only.  I understood what you are saying. Will do that once coding period starts .

**Comment by prathimacode-hub** [comment]
yes, sure. Coding period started @SabariGanesh-K

**Comment by soumali28** [comment]
I want to contribute to this project under JWOC.

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC

**Comment by SabariGanesh-K** [comment]
> yes, sure. Coding period started @SabariGanesh-K 

Yeah Okay.. Assign if possible

**Comment by prathimacode-hub** [comment]
Issue is assigned to @soumali28 on FCFS basis

@codervivek5, there are much such issues arriving to explore.
