### ISSUE TITLE
MedFlare : Make the folder and file structure 

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/MedFlare#17]
Hey JWOC participants, good to see you.

This issue's goal is to make a folder and file structure

If you are not aware about how to semantically make a folder or file structure for the web, you may refer to the following links for reference:

- [Appcropolis](https://appcropolis.com/blog/web-technology/organize-html-css-javascript-files/)
- [Pixinvent](https://pixinvent.com/demo/vuexy-html-bootstrap-admin-template/documentation/documentation-folder-structure.html)
- [Medium](https://medium.com/@nmayurashok/file-and-folder-structure-for-web-development-8c5c83810a5)

How to get it approved?

- Add a screenshot of  outlook on this thread and wait for one of the mentors to get back to you.
- Once it's approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/MedFlare/blob/main/CONTRIBUTING.md) at least once before contributing code to MedFlare

**Comment by Riddhi9570** [comment]
I want to work on this issue under JWOC.

**Comment by prathimacode-hub** [comment]
Yeah, go ahead. Issue assigned to @Riddhi9570

**Comment by Riddhi9570** [comment]
![Screenshot (15)](https://user-images.githubusercontent.com/72887868/152324425-235b23fa-61fe-41bc-b4a8-036e98f3cbe3.png)
Is it fine?

**Comment by prathimacode-hub** [comment]
Looks perfect. You can proceed. @Riddhi9570

**Comment by Riddhi9570** [comment]
@prathimacode-hub I want to discuss something. I have messaged in discord. Please check.
