### ISSUE TITLE
MedFlare: Make a "Blogs" Page with Blog Cards

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/MedFlare#18]
Hey JWOC participants, good to see you.

Build a MedFlare Blog Page with multiple cards that have some text block and accompanying images. Follow the following as a part of your checklist.

- Make sure that the images you use are uncopyrighted (Some sources are [Pexels](https://www.pexels.com/), [Pixabay](https://pixabay.com/), [Unsplash](https://unsplash.com/images) ).
- Use MedFlare relevant text and images (feel free to use your creativity)
- Make sure that Blog is linked in all correct places (navbar, footer, etc.)

Feel free to use the below link as a reference:
[Blog Top 50](https://detailed.com/50/)

How to get it approved?

- Add a screenshot of  outlook on this thread and wait for one of the mentors to get back to you.
- Once it's approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/MedFlare/blob/main/CONTRIBUTING.md) at least once before contributing code.

**Comment by Srijita-Mandal** [comment]
Can I work on this issue under JWoC?

**Comment by prathimacode-hub** [comment]
Yes, you can. Go ahead. Issue assigned to @Srijita-Mandal

**Comment by prathimacode-hub** [comment]
Issue update please? @Srijita-Mandal

**Comment by Srijita-Mandal** [comment]
I haven't start it till now. Can you please unassign me from this issue?

**Comment by prathimacode-hub** [comment]
You have unassigned yourself itself. There is no point in asking me to unassign. @Srijita-Mandal

**Comment by aditi-gosain** [comment]
I want to work on this issue under JWOC.

**Comment by prathimacode-hub** [comment]
Issue assigned to @aditi-gosain

**Comment by 03amir** [comment]
I want to work on this issue under JWOC.

**Comment by prathimacode-hub** [comment]
@aditi-gosain update please?

**Comment by zugzwang03** [comment]
Hey Prathima ma'am, I want to work on this issue under JWOC.

**Comment by prathimacode-hub** [comment]
It's been more than 8 days since issue is assigned and no update from your end so unfortunately, this issue is handed to next person on queue. Better luck next time. @aditi-gosain 

Issue is assigned to @03amir to be a next person on queue. you can proceed. Hope you understand what this issue needs

@zugzwang03 You are on queue.

**Comment by zugzwang03** [comment]
Hey Prathima ma'am, will I work on this issue under JWOC then?

**Comment by prathimacode-hub** [comment]
Yes, you can start working on this issue. @zugzwang03 

Since no response from you for past 3 days about confirmation of taking up an issue, it's assigned to next person. Holding the issue and removing the assignment on your own without informing isn't right. @03amir

**Comment by zugzwang03** [comment]
Ma'am, the multiple cards containing text block and accompanying images will be about the various services offered in medFlare?

**Comment by zugzwang03** [comment]
@prathimacode-hub ma'am, I made the blog page. Can you please tell me where to add this page? Is it after the "About" section of the website?
![medflare1](https://user-images.githubusercontent.com/95460021/154484073-1e5112cd-faa2-4933-87c9-482b6ef0c9b2.png)
![medflare2](https://user-images.githubusercontent.com/95460021/154484111-9c507c98-38bc-45de-866c-d9d5f08b87b4.png)

**Comment by prathimacode-hub** [comment]
This is good, but it's like showing the services provided. You do one thing. You add this below About section in Services. And similar to this, add it in using scroll front and back arrow above footer section in Home page. It should have a learn more option since this is a blog. When it's clicked the concerned blog should open in a new page. for this Create separate blog page as well which directs to an individual blog. @zugzwang03

**Comment by zugzwang03** [comment]
Okay, so the services section will be replaced by my blog page?

**Comment by prathimacode-hub** [comment]
Yes, and initiate a blog page that supports this issue @zugzwang03

**Comment by Sanghu01** [comment]
I would like to work on this issue under JWOC. I also want to work in this issue plz also assign me

**Comment by prathimacode-hub** [comment]
@Sanghu01 Will let you know by evening
