### ISSUE TITLE
MedFlare: Add medical themed carousel to homepage

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/MedFlare#19]
Hey JWOC participants, good to see you.

This issue's goal is to create a medical themed carousel to homepage

Add a medical-themed carousel to index.html. Make sure you use uncopyrighted images. Use 4-5 slides in the carousel, heroing different MedFlare features. Feel free to use below reference:

[Texhnext](https://technext.github.io/montana/index.html)

How to get it approved?

- Add a screenshot of  outlook on this thread and wait for one of the mentors to get back to you.
- Once it's approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/MedFlare/blob/main/CONTRIBUTING.md) at least once before contributing code to MedFlare.

**Comment by soujo** [comment]
Hi @prathimacode-hub , I want to work on the issue under JWOC
Do you want to change the whole header section of the index.html with a carousel similar to the link you provided or do you want only to change the doctor's group SVG with the carousel or are you asking to build an entire carousel section?
Kindly elaborate.

**Comment by RajulPE** [comment]
I am interested in working on this issue under JWOC.

**Comment by prathimacode-hub** [comment]
Create a carousel in body section of the website. This is only an addition to the body page. Don't change or remove anything from the header or other things. @soujo

**Comment by prathimacode-hub** [comment]
@RajulPE, you can comment on other open issues

**Comment by soujo** [comment]
> Create a carousel in body section of the website. This is only an addition to the body page. Don't change or remove anything from the header or other things. @soujo

Okay sure , I am working on it

**Comment by soujo** [comment]
@prathimacode-hub , so should I include the carousel above about section?

**Comment by prathimacode-hub** [comment]
Yes, exactly @soujo

**Comment by soujo** [comment]
Kindly see the video and give feedback @prathimacode-hub 
I have used the terms and pictures according to the services it will endorse ( in your README.md )

https://user-images.githubusercontent.com/78646418/152296684-7e79b0c3-c9c0-4428-98d9-284b0e25842d.mp4

**Comment by prathimacode-hub** [comment]
Can you use some other images. It isn't going well with the theme of website. It's of emergency aid one. So these are related to treatments and hospital based. @soujo

**Comment by soujo** [comment]
> Can you use some other images. It isn't going well with the theme of the website. It's of emergency aid one. So these are related to treatments and hospital based. @soujo

Yeah sure, I will make the changes
The text which is shown over the pictures, is that okay? Do I need to change those texts too or only the pictures?
Actually, I searched the pictures with those texts itself @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Oh, don't search that way. Instead use canva or photoshop to insert text to the images and do modifications according to theme. Keeping images directly isn't going well and bland too. Hope you'll use uncopyrighted images. And also don't show people in images.

For slides, use only 4 images in total. I will give some references. @soujo

**Comment by soujo** [comment]
Can we do something like this ? @prathimacode-hub 
I tried in Canva. It's just a test sample.

![MedFlare](https://user-images.githubusercontent.com/78646418/152303731-3e787ea0-6749-4bac-9133-2b445b415317.png)

**Comment by prathimacode-hub** [comment]
Yes, we can do this way, Here instead of mentioned the words of Vaccination Centers Notification or Oxygen Cylinder Supply. Use generalized words that define the problem statement. This would be more particular. But image is good
I will send few images and format to you for reference in discord. @soujo

**Comment by soujo** [comment]
Is this okay ? @prathimacode-hub 

https://user-images.githubusercontent.com/78646418/152339395-9823f838-3f70-41e8-b3f7-618409952842.mp4
