### ISSUE TITLE
MedFlare : Vaccination Centers Notification

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/MedFlare#2]
Hey Hacktoberfest participants, good to see you.

This issue's goal is to get the glimpse of all the vaccination centers with availability notification sent to the user

How to get it approved?

- Add a screenshot and video of outlook on this thread and wait for one of the mentors to get back to you.
- Once it's approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/MedFlare/blob/main/CONTRIBUTING.md) at least once before contributing code.

**Comment by r3yc0n1c** [comment]
I would like to work on this issue under JWoC'22

**Comment by Devmindtk** [comment]
I would like to work on this issue under JWOC'22. please assign to me @prathimacode-hub

**Comment by r3yc0n1c** [comment]
Hey @prathimacode-hub, I would like to continue my work on this issue under JWoC'22

**Comment by prathimacode-hub** [comment]
Issue assigned to @Devmindtk on FCFS basis

@r3yc0n1c, Sorry you missed the line by 2mins difference. I'm adding new issues now for you to grab upon.

**Comment by Devmindtk** [comment]
i have to do backend here or only ui part of getting notification?

**Comment by prathimacode-hub** [comment]
Both. Update please? @Devmindtk

**Comment by akashyap25** [comment]
@prathimacode-hub Hey, just wanted to know if we have to send notification to the user as mail or message or just show available centres on the website itself, when they search using district or pincode

**Comment by prathimacode-hub** [comment]
Showcase it over the Website itself. For mail and message notification, that will come up as an another issue. @akashyap25

**Comment by akashyap25** [comment]
I am interested in completing this task, Please assign it to me.

**Comment by prathimacode-hub** [comment]
Issue assigned to @akashyap25
