### ISSUE TITLE
Project Admin Image for MedFlare home page is not being displayed.

### ISSUE THREAD

**Issue by Debdeep1** [prathimacode-hub/MedFlare#26]

**Comment by Debdeep1** [comment]
I want to work on this issue under JWOC

**Comment by prathimacode-hub** [comment]
Issue assigned to @Debdeep1 but this won't count under JWOC. In your issue comment using edit, add issue template and provide details about this issue. As here we have only 3 kind of label. This works only if we have 4 or more than 5 labels.

**Comment by prathimacode-hub** [comment]
In your issue comment using edit, add issue template and provide details about this issue. @Debdeep1

**Comment by prathimacode-hub** [comment]
No response? @Debdeep1
