### ISSUE TITLE
MedFlare : Bed Availability Notification

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/MedFlare#3]
Hey JWOC participants, good to see you.

This issue's goal is to get the bed availabilities across the city and sent notification to user

How to get it approved?

- Add a screenshot and video of outlook on this thread and wait for one of the mentors to get back to you.
- Once it's approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/MedFlare/blob/main/CONTRIBUTING.md) at least once before contributing code.

**Comment by r3yc0n1c** [comment]
I would like to work on this issue under JWoC'22

**Comment by prathimacode-hub** [comment]
You have expressed interest for 2 issues. So let me know of the issue you would like to start with? @r3yc0n1c

**Comment by r3yc0n1c** [comment]
let me get started with this one first

**Comment by prathimacode-hub** [comment]
Sure, you can proceed working @r3yc0n1c

**Comment by prathimacode-hub** [comment]
Update please? @r3yc0n1c
