### ISSUE TITLE
Clicking on "Get Started" on "https://prathimacode-hub.github.io/MedFlare/" not redirecting to any page or link

### ISSUE THREAD

**Issue by iatharva** [prathimacode-hub/MedFlare#31]
I think currently it's in development that's why maybe it's not implemented yet. But do look into the issue, cause as a new person/visitor that's the first action which I can see clearly. So, do add link into the Button.

**Comment by prathimacode-hub** [comment]
You added a right point. Sign up thing isn't approved yet since that is yet to link to get started option @iatharva
