### ISSUE TITLE
Responsiveness of Home Page 

### ISSUE THREAD

**Issue by Shruti025** [prathimacode-hub/MedFlare#33]
The home page of the website has bugs in responsiveness.

![image](https://user-images.githubusercontent.com/72005584/155533669-c7d7b8f1-b2cb-44d3-9cf5-9ea6fa690739.png)
![image](https://user-images.githubusercontent.com/72005584/155533723-79adcf52-3071-4d9e-999a-25125535dd5a.png)

**Comment by Shruti025** [comment]
I want to work on this issue under JWOC

**Comment by prathimacode-hub** [comment]
Yes, sure. Issue assigned to @Shruti025
