### ISSUE TITLE
MedFlare : Create About Section for Website

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/MedFlare#4]
Hey JWOC participants, good to see you.

This issue's goal is to create an external layout of about page of the website.

Feel free to be creative! And please take care of the following criteria:

- In the page, add relevant text and also a related image (feel free to use any uncopyrighted images or graphics)
- Include textual contact details along with contact form on to the right 

You can refer this link for reference : https://www.tripodeal.com/travel/about-us/

How to get it approved?

- Add a screenshot of  outlook on this thread and wait for one of the mentors to get back to you.
- Once it's approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/MedFlare/blob/main/CONTRIBUTING.md) at least once before contributing code.

**Comment by vivekpatel17** [comment]
I would like to work on this issue under JWoC.

**Comment by prathimacode-hub** [comment]
Issue will be assigned to person on FCFS basis from 12AM onwards. So one who express their interest first after 12AM will be considered to be assigned this issue. So see you in few more mins @vivekpatel17

**Comment by vivekpatel17** [comment]
I would like to work on this issue under JWoC.

**Comment by prathimacode-hub** [comment]
Issue assigned to @vivekpatel17

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC
