### ISSUE TITLE
MedFlare : Doctors Appointment Form

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/MedFlare#40]
Hey JWOC participants, good to see you.

This issue's goal is to provide a doctor appointment form that needs to be filled with basic patient details along with location, preferred doctor, available time slots and get it notified by email and phone to the user.

How to get it approved?

- Add a screenshot and video of outlook on this thread and wait for one of the mentors to get back to you.
- Once it's approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/MedFlare/blob/main/CONTRIBUTING.md) at least once before contributing code.

**Comment by soujo** [comment]
I would like to work on this issue under JWOC
@prathimacode-hub

**Comment by prathimacode-hub** [comment]
Issue assigned to @soujo

**Comment by soujo** [comment]
Could you kindly confirm the fields which I have to add?
Also, do you have any references? @prathimacode-hub
