### ISSUE TITLE
MedFlare : Book Your Ambulance

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/MedFlare#41]
Hey Hacktoberfest participants, good to see you.

This issue's goal is to provide a booking your ambulance form that needs to be filled with basic details that tracks your location and sends you up with the nearest hospital details according to the symptoms you're facing. It fetches you with a booked invoice to your email and phone number.

How to get it approved?

- Add a screenshot and video of outlook on this thread and wait for one of the mentors to get back to you.
- Once it's approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/MedFlare/blob/main/CONTRIBUTING.md) at least once before contributing code.

**Comment by r3yc0n1c** [comment]
I would like to work on this issue under JWoC'22

**Comment by prathimacode-hub** [comment]
Issue assigned to @r3yc0n1c

**Comment by prathimacode-hub** [comment]
Update please? @r3yc0n1c

**Comment by Aankirz** [comment]
Hey @prathimacode-hub I would like to solve this issue.

**Comment by prathimacode-hub** [comment]
Issue assigned to @Aankirz

**Comment by Aankirz** [comment]
Hey @prathimacode-hub I've made the "Book your ambulance page".
####  With all the necessary inputs.

#### ✅ Auto-detect Location
#### ✅ Send Invoices to the entered mail ID from "my ID (as of now)".

#### Here's the screenshot
<img width="1440" alt="Screenshot 2022-10-05 at 5 58 52 PM" src="https://user-images.githubusercontent.com/95562947/194060354-5a5c1662-ded0-4ef3-9ccf-e69a73ec92c0.png">
<img width="1440" alt="Screenshot 2022-10-05 at 6 00 30 PM" src="https://user-images.githubusercontent.com/95562947/194060644-9f120dff-adde-42fe-ba7e-f6eb82db07a1.png">

**Comment by Aankirz** [comment]
Here's the video link ->

#### https://youtu.be/OFOeiSMMZPM
