### ISSUE TITLE
Transition Effect on hovering services card

### ISSUE THREAD

**Issue by Faraaz2633** [prathimacode-hub/MedFlare#42]
Hey there, 
When we hover the Services card it suddenly pops out so i would like to add some transitions effects in it so it would look good.
I would like to this under JWOC.

**Comment by prathimacode-hub** [comment]
Can you add the issue template along with issue details to get it assigned. @Faraaz2633

**Comment by Faraaz2633** [comment]
![image](https://user-images.githubusercontent.com/73326287/156909176-fa6b8383-b11a-46c1-9c44-29b9a0a81442.png)

On bigger screens, the Why us section has an improper alignment.

**Comment by prathimacode-hub** [comment]
Can you add the issue template so that i could assign this issue to you? @Faraaz2633
