### ISSUE TITLE
UI Change needed

### ISSUE THREAD

**Issue by Faraaz2633** [prathimacode-hub/MedFlare#44]
Hey there,
I would love to change the entire UI of this project with Tailwind CSS.
There are lots of issues with the current UI.
I would like to work under JWOC.
I would be very grateful if you could assign this issue to me.

**Comment by Faraaz2633** [comment]
![image](https://user-images.githubusercontent.com/73326287/156909390-147f1e20-6962-4a61-8abe-effc3753e156.png)

**Comment by Faraaz2633** [comment]
![image](https://user-images.githubusercontent.com/73326287/156909408-0a605377-5b94-4920-9249-8452a2832bbc.png)

**Comment by Faraaz2633** [comment]
![image](https://user-images.githubusercontent.com/73326287/156909425-17981ab0-eb9e-4321-86d6-6f810181dbf4.png)

**Comment by prathimacode-hub** [comment]
Sure, you can proceed. Issue assigned. @Faraaz2633

**Comment by prathimacode-hub** [comment]
Update please? @Faraaz2633
