### ISSUE TITLE
Unresponsive Website 

### ISSUE THREAD

**Issue by itshypon** [prathimacode-hub/MedFlare#45]
---
Title: Unresponsive Website
About: Website is unresponsive in mobile ie it's webpage doesn't load like it should in other devices, it's elements are static instead of changes it's position and size according to page
Name: Himanshu
Label: Feature Request
Assignee: ''

---

Define You:

- [x] Hacktoberfest Participant
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

Website is unresponsive in mobile ie it's webpage doesn't load like it should in other devices, it's elements are static instead of changes it's position and size according to page

**Describe the solution you'd like...**

I will make this website responsive, pages will load perfectly without any collapse in mobile or other devices

**Additional context**

Open the website in android to see the issue.

**Comment by prathimacode-hub** [comment]
Issue has been assigned to @itshypon. Proceed forward.

**Comment by prathimacode-hub** [comment]
You can be specific about the task on the issue instead of just mentioned Unresponsive Website, so that's it clearly understood. @itshypon

**Comment by prathimacode-hub** [comment]
Can you include the issue template here along with the issue details? @itshypon

**Comment by itshypon** [comment]
@prathimacode-hub Done, will start working soon on it between 12-15.

**Comment by prathimacode-hub** [comment]
Update please? @itshypon

**Comment by itshypon** [comment]
@prathimacode-hub Will submit PR by today or tomorrow.

**Comment by itshypon** [comment]
@prathimacode-hub I just noticed that the unresponsiveness issue is no more coming in the website. Looks like it's fixed in other PRs. I will close this issue and work on Ezy-Parking one then.
