### ISSUE TITLE
UI Suggestions

### ISSUE THREAD

**Issue by mateahoward** [prathimacode-hub/MedFlare#46]
Hi! I've got a few suggestions I'd like to add to your project if you'd like me to. They are:

SEO:
- add a meta description 
- remove multiple `<h1>` elements 

Accessibility:
- make sure all images have alt text attributes on them 
- make sure all background colors have a sufficient contrast ratio (specifically for the 'CTA-1' and 'CTA-2' buttons)
- make sure all interactive elements receive styling for when they're in focus

If you'd like me to start working on this, please assign the issue to me 😄

**Comment by prathimacode-hub** [comment]
Issue assigned to @mateahoward. You can proceed forward.

**Comment by Anikaaasingh** [comment]
Hey @prathimacode-hub  I would like to improve the ui of ABOUT section with following change.
1.Put bg color acc to color pallete of site
2.Shift pic to right and text to left
3.Add css on hover animation  in background to make it interactive . Reference image of animation  is
![Screenshot_20221001-202828_YouTube](https://user-images.githubusercontent.com/96921017/193415552-35a65035-3260-4546-a47c-ab5cbf5a3ba1.jpg)
Heart png can be replaced by circles as you would prefer.
May I work on it?

**Comment by prathimacode-hub** [comment]
You can create an issue with these details separately to get it assigned. Tag me when you do so over that issue. @Anikaaasingh

**Comment by mateahoward** [comment]
Hi @prathimacode-hub 😄 I submitted a PR over here, if you agree with the changes then this issue can be closed 💪 
https://github.com/prathimacode-hub/MedFlare/pull/47

**Comment by prathimacode-hub** [comment]
You're super fast. I'll review onto the PR in 5mins. @mateahoward

**Comment by prathimacode-hub** [comment]
Why have you closed it? Kindly don't close. It closes automatically when PR is merged successfully with issue number. @mateahoward
