### ISSUE TITLE
UI improvement of About Section.

### ISSUE THREAD

**Issue by Anikaaasingh** [prathimacode-hub/MedFlare#48]
Hey @prathimacode-hub I would like to improve the ui of ABOUT section with following change.
1.Put bg color acc to color pallete of site
2.Shift pic to right and text to left
3.Add css on hover animation in background to make it interactive . Reference image of animation is
![Screenshot (270)](https://user-images.githubusercontent.com/96921017/193417606-2dd03fde-d305-41cc-94a7-fcb6e8ca55b3.png)

Heart png can be replaced by circles as you would prefer.
May I work on it?

**Comment by Anikaaasingh** [comment]
![Screenshot (271)](https://user-images.githubusercontent.com/96921017/193419214-23d70c8b-7b11-42b6-ad4b-5133769e67a5.png)
This is coming after running code locally whereas,
![Screenshot (272)](https://user-images.githubusercontent.com/96921017/193419241-782a9e6f-9ff2-44ac-8c1d-17172f19310a.png)
This is the link put by you. @prathimacode-hub kindly guide

**Comment by prathimacode-hub** [comment]
Oops, I don't know what's wrong. Let me check. @Anikaaasingh

**Comment by prathimacode-hub** [comment]
Couldn't figure out any issue from my end. Don't know what's wrong. Refork it with the latest changes to see if it works. @Anikaaasingh

**Comment by prathimacode-hub** [comment]
Got it. The thing is we have 2 formats of this app : 1 is using html, css and js and 2 is using react based for MedFlare. So you do the changes for react based app. @Anikaaasingh

**Comment by Anikaaasingh** [comment]
What command do I have to use to set react site. Using npm start is leading to the first format?

**Comment by prathimacode-hub** [comment]
Do you want any resource to it? @Anikaaasingh

**Comment by prathimacode-hub** [comment]
@Anikaaasingh, can you provide an update on this?

**Comment by prathimacode-hub** [comment]
Why have you closed it without informing? @Anikaaasingh
