### ISSUE TITLE
Clicking on Navbar Buttons does nothing. 

### ISSUE THREAD

**Issue by Amiyanshu-web** [prathimacode-hub/MedFlare#49]
Clicking on Navbar buttons(Home, About Us, Services...) should take them to their respective sections which is not happening.

![home](https://user-images.githubusercontent.com/59080551/193749988-35087483-0d4c-4ae8-8700-a9ff106b38c8.gif)

**Comment by 3xp11i** [comment]
Hey can you please assign me to this issue? I can resolve this issue. @prathimacode-hub

**Comment by 3xp11i** [comment]
Please check my [PR](https://github.com/prathimacode-hub/MedFlare/pull/50)

**Comment by prathimacode-hub** [comment]
You have created a PR without getting assigned. @prakhartiwari0 

Anyways, this issue is too small to be done. Come up with a valid and legible issue. @Amiyanshu-web @prakhartiwari0

**Comment by Amiyanshu-web** [comment]
> You have created a PR without getting assigned. @prakhartiwari0
> 
> Anyways, this issue is too small to be done. Come up with a valid and legible issue. @Amiyanshu-web @prakhartiwari0

Actually, I was not aware that small issues can not be created. As per my knowledge, I found this issue valid. 
Would love to know what exactly valid issues look like. 
Anyways, thanks for letting me know.

**Comment by 3xp11i** [comment]
> You have created a PR without getting assigned. @prakhartiwari0

I am very sorry @prathimacode-hub, I am new to Open Source, and will learn from this mistake 👍. 

> Anyways, this issue is too small to be done. Come up with a valid and legible issue. @Amiyanshu-web @prakhartiwari0

I don't think this issue is too small, as navigation plays an important role in the functioning of a website. If the navbar cannot be used, it spoils the experience of the user. It literally isn't working, so this should be resolved.

I want to improve the UI of the services section, I have opened an issue, please check  #51

**Comment by prathimacode-hub** [comment]
This issue is fine, but can include some more changes to it. At the end, I want contributions that goes into this project should be counted. Don't be sorry. @prakhartiwari0 

@Amiyanshu-web I emphasize that PR's shouldn't be discarded from Hacktoberfest. That's my only concern.

**Comment by prathimacode-hub** [comment]
Oops, @prakhartiwari0 got it assigned. @Amiyanshu-web, can you come up with an another issue.
