### ISSUE TITLE
MedFlare : Create Contact Section for Website

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/MedFlare#5]
Hey JWOC participants, good to see you.

This issue's goal is to create an external layout of contact page of the website.

Feel free to be creative! And please take care of the following criteria:

- In the page, add an embedded map with dummy location
- Include textual contact details along with contact form on to the right 

You can refer this link : http://cpconsol.com/contact-us.html

How to get it approved?

- Add a screenshot of  outlook on this thread and wait for one of the mentors to get back to you.
- Once it's approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/MedFlare/blob/main/CONTRIBUTING.md) at least once before contributing code.

**Comment by snega16** [comment]
Hey I have a doubt. Contact page in the sense, we should develop the contact section with more details from users like name, email, ph, etc?

**Comment by combatantash** [comment]
I want to work on this issue under JWOC

**Comment by prathimacode-hub** [comment]
Issue assigned to @combatantash

**Comment by combatantash** [comment]
Unassign the issue for me.

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC

**Comment by prathimacode-hub** [comment]
Update please @combatantash

**Comment by boradesanket13** [comment]
I want to work on this issue under JWOC. I would like to contribute on this issue. Kindly assign this issue to me.

**Comment by prathimacode-hub** [comment]
Issue assigned to @Sanket1308 and @codervivek5 first we will complete the assigned issue and change that needs to be done.

Don't worry ample of issues coming up.

**Comment by prathimacode-hub** [comment]
@combatantash, Deadline is up. Sorry. We have other issues coming too. But try to complete it on time. And even if you couldn't atleast update and inform so that we can extend some time instead of holding up.
