### ISSUE TITLE
UI Improvement of the Services Section

### ISSUE THREAD

**Issue by 3xp11i** [prathimacode-hub/MedFlare#51]
## The current Services Section looks like this on a large screen
*Please ignore the **blood donor availability** card, it is the problem with the screenshot extension.*
[Screenshot 1](https://user-images.githubusercontent.com/65062036/193992414-28d3fbb4-b246-49db-851e-9d2e5b1056fc.png)

## On *My Screen*, it is really *messed up* as you can see
[Screenshot 2](https://user-images.githubusercontent.com/65062036/193993524-644fc13a-ba8f-4d64-b591-464348ec3d6a.png)

## Improvements that can be made
- We can make the size of the card smaller and more readable rather than being long in height.
- Cards can be arranged in a better way to easily access them (Some cards are messed up as you )
- Each card size can be made consistent as if you notice some cards are bigger than the others.

**Comment by 3xp11i** [comment]
If you find this issue legible, kindly assign it to me so that I can work on it. @prathimacode-hub

**Comment by 3xp11i** [comment]
> Hello there! 👋🏻 Welcome to the MedFlare! rocketzap Thank you and congrats tada for opening your very first issue in this project. Please adhere to our [Code of Conduct](https://github.com/prathimacode-hub/MedFlare/blob/main/CODE_OF_CONDUCT.md). 👍🏻 You may submit a PR if you like, make sure to follow our [Pull Request Template](https://github.com/prathimacode-hub/MedFlare/blob/main/.github/pullrequest_template.md). Feel free to get in touch with me through social media handles. Hope to see you there!smile

BotBro the Pull Request Template link is not working, kindly check @prathimacode-hub 😅

**Comment by prathimacode-hub** [comment]
PR template is working for me. Issue assigned to @prakhartiwari0

**Comment by 3xp11i** [comment]
> PR template is working for me.

![image](https://user-images.githubusercontent.com/65062036/194319722-6faffde4-d699-4884-abac-ff25b0a9c92d.png)

Maybe a problem from my end. 

> Issue assigned to @prakhartiwari0

Thanks! Will start working on it and ask for feedback so that I can make this section, and the whole project better!
