### ISSUE TITLE
Improve the Design of Bed Availability Notification Form Page

### ISSUE THREAD

**Issue by 3xp11i** [prathimacode-hub/MedFlare#56]
## Issue 
The form is really bad and is overlapping the image on the left. It is also not reponsive

## Screenshot
![image](https://user-images.githubusercontent.com/65062036/194764336-ec871ae4-b114-482c-bf5f-aef2acdcbd4d.png)

## Solution 
I can work on this issue and improve the UI of the form very much +  Make it responsive also

**Comment by prathimacode-hub** [comment]
Issue assigned to @prakhartiwari0

**Comment by 3xp11i** [comment]
Thanks!
