### ISSUE TITLE
Improve the functionality of the home page

### ISSUE THREAD

**Issue by 3xp11i** [prathimacode-hub/MedFlare#57]
## Issue
This issue has multiple issues inside it to address:
- The links buttons in the cards of the Services Section are not working properly
- The Navigation bar is not working either (This issue is already raised in #49 but the maintainer asked to include some more problems to make it legible, so this is it)

If you want @prathimacode-hub then you can close the previous issue and assign this issue to me so that I can work on all of those problems.

## Solution 
I can work on this issue and make all of this work properly

**Comment by prathimacode-hub** [comment]
Issue assigned to @prakhartiwari0

**Comment by 3xp11i** [comment]
Thanks!

**Comment by 3xp11i** [comment]
## Update on the issue

- There are a lot of new issues that are created due to the changes in the file structure, I am going to solve them too..

**Comment by prathimacode-hub** [comment]
Update please? @prakhartiwari0

**Comment by 3xp11i** [comment]
> Update please? @prakhartiwari0

yes I am sorry to take time, I am going through some health issues. Will try to complete it today.
