### ISSUE TITLE
Refactoring and Migration

### ISSUE THREAD

**Issue by Ardent10** [prathimacode-hub/MedFlare#58]
The Current Project is a mix of both basic html,css,js and a React Application, 
I would like to structure this project so that we can Implement the functionalities using React only and Html ,css and Js are not that flexible in terms of Reusability.
![image](https://user-images.githubusercontent.com/73132031/194774133-820a69ed-57ee-474b-bd2a-097a8cc96cb5.png)

**Comment by prathimacode-hub** [comment]
Issue assigned to @Ardent10
