### ISSUE TITLE
MedFlare : Create Complete Sign Up / Login Details of Website

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/MedFlare#6]
Hey JWOC participants, good to see you.

This issue's goal is to create an an overall sign up and login process of the website.

Feel free to be creative! And please take care of the following criteria:

- Create a user friendly sign up and login process 
- Add authentication procedure to it with basic database structure and open it in dashboard format

How to get it approved?

- Add a screenshot of  outlook on this thread and wait for one of the mentors to get back to you.
- Once it's approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/MedFlare/blob/main/CONTRIBUTING.md) at least once before contributing code.

**Comment by Rik-21** [comment]
can i work on it please

**Comment by prathimacode-hub** [comment]
To get yourself assigned, kindly express your interest from 12AM 1st Feb. That's when the issue is valid for counting. Are you a JWoC Participant? @Rik-21

**Comment by Rik-21** [comment]
> To get yourself assigned, kindly express your interest from 12AM 1st Feb. That's when the issue is valid for counting. Are you a JWoC Participant? @Rik-21

Yes I am a JWoC participant  . Sorry i really did not knew about the 1 feb rule

**Comment by prathimacode-hub** [comment]
No worries @Rik-21

**Comment by Rik-21** [comment]
"I want to work on this issue under JWOC"
Can i work on this issue ?

**Comment by combatantash** [comment]
I want to work on this issue under JWOC

**Comment by prathimacode-hub** [comment]
Issue assigned to @Rik-21 on FCFS basis. You can choose some other issue @combatantash

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC
