### ISSUE TITLE
improving features like adjusting the position of images in bed.html, making cursor pointer on the Medflare logo etc.

### ISSUE THREAD

**Issue by ritishbhardwaj** [prathimacode-hub/MedFlare#60]

**Comment by ritishbhardwaj** [comment]
@prathimacode-hub 
assign this issue to me

**Comment by ritishbhardwaj** [comment]
https://user-images.githubusercontent.com/81488252/194865914-dab1ed5b-cb59-4a03-a06f-4b55ffa79b50.mp4

all changes in one video that i have made
you can refer original web page for comparison

if you like this small change then we can talk further

**Comment by Rishikavishnoi** [comment]
Issue assigned to @Ardent10  and also make bed.html page more responsive

**Comment by Rishikavishnoi** [comment]
Issue assign to @ritishbhardwaj and work on the responsiveness of the bed.html page

**Comment by prathimacode-hub** [comment]
Issue assigned to @ritishbhardwaj

**Comment by prathimacode-hub** [comment]
Update please and add the issue template above along with issue details as well? @ritishbhardwaj

**Comment by prathimacode-hub** [comment]
Update please? @prathimacode-hub
