### ISSUE TITLE
Homepage Hero component

### ISSUE THREAD

**Issue by Ardent10** [prathimacode-hub/MedFlare#65]
The current React project only has the About section on Top I would like to create a Hero Component for MedFlare.
@Rishikavishnoi @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Issue assigned to @Ardent10. Kindly add the issue template here along with the issue details.

**Comment by prathimacode-hub** [comment]
Update? @Ardent10

**Comment by Ardent10** [comment]
> Update? @Ardent10
Working on it. @prathimacode-hub

**Comment by Ardent10** [comment]
> Update? @Ardent10 

Working on it will make a pr soon. @prathimacode-hub
