### ISSUE TITLE
Medflare Layout with Footer.

### ISSUE THREAD

**Issue by Ardent10** [prathimacode-hub/MedFlare#67]
I would like to complete the layout of the project with a footer.

**Comment by prathimacode-hub** [comment]
Issue assigned to @Ardent10. Kindly add the issue template here along with the issue details.

**Comment by prathimacode-hub** [comment]
Update? @Ardent10

**Comment by Ardent10** [comment]
> Update? @Ardent10

Will make their PR at once.
