### ISSUE TITLE
MedFlare : Create a Header Section of Home Page 

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/MedFlare#7]
Hey JWOC participants, good to see you.

This issue's goal is to create a header section of home page which also includes Navigation bar of medical webapp

Feel free to be creative! And please take care of the following criteria:

- create header along with Navigation Bar with 6 options
- Try and get the structure approved before making final pr.

How to get it approved?

- Add a screenshot of  header on this thread and wait for one of the mentors to get back to you.
- Once it's approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/MedFlare/blob/main/CONTRIBUTING.md) at least once before contributing code.

**Comment by soujo** [comment]
Hey @prathimacode-hub , I am interested to work on this issue under JWOC,
Do you have some design in mind ? or some other files which I can refer to, as there is no base for this project from where I can understand.

**Comment by prathimacode-hub** [comment]
I can provide a reference file for it to take it as a consideration. Since this project is from scratch it has no basic files right now. @soujo

**Comment by prathimacode-hub** [comment]
Issue assigned to you. I will send you the link to refer in a moment @soujo

**Comment by soujo** [comment]
Sure , Thanks

**Comment by prathimacode-hub** [comment]
Refer these 2 links for references to create a header section :

https://www.petermac.org/ 
https://www.alfredhealth.org.au/

@soujo

**Comment by soujo** [comment]
Hey @prathimacode-hub 
Kindly give feedback on the screenshot, is this fine for the header?
Then I would proceed with this one
![Screenshot (190)](https://user-images.githubusercontent.com/78646418/152097195-ee7bef7d-8ba0-488b-91bf-a612ff4d34ff.png)

**Comment by prathimacode-hub** [comment]
Yes, this is good. You can go ahead with creating the PR. @soujo
