### ISSUE TITLE
MedFlare : Create a Footer Section for the Home Page 

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/MedFlare#8]
Hey JWOC participants, good to see you.

This issue's goal is to create a footer section of home page which also includes Navigation bar of medical webapp

Feel free to be creative! And please take care of the following criteria:

- create atleast 4 rows with Quick Links and Basic Footer Data
- Try and get the structure approved before making final pr.

How to get it approved?

- Add a screenshot of footer on this thread and wait for one of the mentors to get back to you.
- Once it's approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/MedFlare/blob/main/CONTRIBUTING.md) at least once before contributing code.

**Comment by ronitblenz** [comment]
Hi, I want to work in this issue, 
Please let me in as an assignee

Thanks

**Comment by prathimacode-hub** [comment]
Are you a JWOC Participant? @ronitblenz

**Comment by ronitblenz** [comment]
Yes I am JWOC Participant

**Comment by prathimacode-hub** [comment]
Hope you know the timeline to complete the issue. Issue is assigned to @ronitblenz
