### ISSUE TITLE
MedFlare : Make MedFlare logo and favicon

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/MedFlare#9]
Hey JWOC participants, good to see you.

Feel free to be creative! And please take care of the following criteria:

- upload two versions of both logo and favicon- one with white bg and another with transparent bg.
- name the images semantically (e.g.: logo_bg, logo_wtbg, etc.)
Try and get your designs approved before making final pr.

How to get designs approved?
- Comment your designs on this thread and wait for one of the mentors to get back to you.
- Once your designs are approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/MedFlare/blob/main/CONTRIBUTING.md) at least once before contributing code.

**Comment by ronitblenz** [comment]
Hi, I am interested to work on this issue, Could you please let me in as an assignee.

**Comment by prathimacode-hub** [comment]
Are you a JWOC Participant? @ronitblenz

**Comment by ronitblenz** [comment]
Yes I am a JWOC Participant

**Comment by prathimacode-hub** [comment]
Are you able to work on 2 issues at a time and submit before the deadline 
@ronitblenz

**Comment by ronitblenz** [comment]
Can you specify the deadline?

**Comment by prathimacode-hub** [comment]
Easy issue 1 day, Medium 3 and Hard 5 days @ronitblenz

**Comment by ronitblenz** [comment]
If its 24hrs I can do it.. Already working on #8 .... I need some details... Where can I contact you?

**Comment by prathimacode-hub** [comment]
You can reach out to me on discord @ronitblenz

**Comment by ronitblenz** [comment]
Ok thanks.. I am texting you then

**Comment by prathimacode-hub** [comment]
Yes @ronitblenz

**Comment by ronitblenz** [comment]
Assign me here... I am almost done with the #8

**Comment by prathimacode-hub** [comment]
Issue assigned to @ronitblenz

**Comment by ronitblenz** [comment]
![MEDIFLARE](https://user-images.githubusercontent.com/91361382/152095047-d0651e6c-0dbc-485e-860a-1d34982b042d.png)
Logo is ready, can you please specify regarding the Favicons with detail?

**Comment by ronitblenz** [comment]
I have figured out the favicon, its done
Can you please approve the design so that I can make the PR

**Comment by prathimacode-hub** [comment]
Is it good with favicon? For logo, it shows a good meaning. Kudos to you. Instead of health is wealth, you can keep some other tagline. You know this webapp is about providing medical emergency aid right? So some caption related to it would be better. So as issue mentions we need 4 images in total : both logo and favicon with white and transparent background. If you could add all the 4 images to this thread, then it would be ready to make PR. @ronitblenz

**Comment by ronitblenz** [comment]
Sure... Making the changes

**Comment by prathimacode-hub** [comment]
I also feel the font style can be different too. Just try with new styles and see. What you have sent now is white background. Yes, please. Whichever you feel good for the logo, keep it final. Ok. @ronitblenz

**Comment by ronitblenz** [comment]
Suggest me a tagline please?

**Comment by ronitblenz** [comment]
And is is it necessary to make favicon different from logo?

**Comment by ronitblenz** [comment]
> I also feel the font style can be different too. Just try with new styles and see. What you have sent now is white background. Yes, please @ronitblenz

No, its a transparent one, I have a white bg too

**Comment by prathimacode-hub** [comment]
Ok, actually most keep it different. Due to the size as favicon is 16*16 and logo is of standard size. Just convert it into smaller size to see if the favicon is visibly good @ronitblenz

**Comment by prathimacode-hub** [comment]
> Suggest me a tagline please?

Yeah, will tell in 2mins @ronitblenz

**Comment by prathimacode-hub** [comment]
Tagline : Insta Help you Need/Deserve 

Whichever looks good with Logo. And also while sending the logo image, different into 2 images. One is only pure logo and other is logo with Tagline both in white and transparent background

And for favicon, try if the same logo looks better when it's reduced to favicon size else new one can be created for it. If it's fine, we can go with same image - Here as well since, this is icon. It won't have any tagline. We would be having this image too in both white and transparent background in icon size. @ronitblenz

**Comment by ronitblenz** [comment]
![Medflare (3)](https://user-images.githubusercontent.com/91361382/152099146-d62e0b3e-0e81-414e-a9f7-5c93a35a0fdf.png)
![Medflare (2)](https://user-images.githubusercontent.com/91361382/152099151-23e1b63a-2ba5-46bc-a0a9-a6194301e813.png)
![Medflare (1)](https://user-images.githubusercontent.com/91361382/152099152-426d1d8f-113f-431f-b5de-c775fdda4294.png)
![Medflare](https://user-images.githubusercontent.com/91361382/152099156-cf4fb807-e1e3-4d21-97cb-4062e9d0ffbe.png)
How's the design now?

**Comment by prathimacode-hub** [comment]
This is good, more relevant to our webname 👏@ronitblenz

**Comment by ronitblenz** [comment]
Should I make a PR now?

**Comment by prathimacode-hub** [comment]
Yeah, and what about favicon? @ronitblenz

**Comment by ronitblenz** [comment]
Favicon is ready, includes all device configs

**Comment by prathimacode-hub** [comment]
Ok, go ahead to make a PR. @ronitblenz
